### ISSUE TITLE
Some Chrome extensions styles causes a crash.

### ISSUE THREAD

**Issue by AlmeroSteyn** [timhagn/gatsby-background-image#6]
I was looking at a site that uses this library today (https://marcysutton.com/) and through blind luck I noticed that, when extensions load stylesheets, it causes this component to crash in Chrome. 

I would submit a PR but would take a lot of time to set up an enviroment where I could test this as I do not yet use it myself, so here are my findings.

If you go to the site above, and load this extension: https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh you could try it.

The error happens when the extension has been activated and I attempt a navigation.

In `BackgroundUtils.js` on line 11 the following error occurs:

>`SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules`

From what I could find out it appears that Chrome is the only browser that treats this as an error. From  (https://github.com/odoo/odoo/issues/22517#issuecomment-361217543) it appears that adding the following code fixes this issue:

```
if (sheets[i].hasOwnProperty('rules')) {
```

Once again, I would have loved to do a PR just don't have the time today to get the test environment up to confirm the fix before submitting :-(

**Comment by timhagn** [comment]
Hi @AlmeroSteyn,

would be nice to know which version of `gatsby-background-image` is used on the page mentioned
cause after PR #2 this _should_ be already fixed in `0.2.2`.

The only possibility I see might be wrapping it in a `try ... catch` block, cause as I mentioned in 
my [comment](https://github.com/timhagn/gatsby-background-image/pull/2#issuecomment-453536906) and changes after merging the PR, `hasOwnProperty()` seems to break some styles
completely...

A testing environment may be found at [gbitest](https://github.com/timhagn/gbitest) by the way,
but I'm gonna test it on my own page as soon as I find the time ; ).

**Comment by AlmeroSteyn** [comment]
The page is using version `0.2.2`.

I did not think to check in the closed things for this as it was breaking, hehe.

BUT, I can confirm that in `gbitest` it still fails. I confirmed that `0.2.2` was indeed loaded in `npm_modules`.

I hard edited `BackgroundUtils.js` in `node_modules` and a `try .. catch` indeed solves the issue. The page then renders fine with the extension.

**Comment by timhagn** [comment]
Thanks for checking : )! Gonna try to integrate it later today (and as I just saw, update `gbitest` to use `0.2.2`, too  % ).

**Comment by AlmeroSteyn** [comment]
Yeah forgot to mention. I did bump before I tested though :-)

Thanks!

**Comment by timhagn** [comment]
https://www.w3.org/TR/cssom-1/#the-cssstylesheet-interface

**Comment by timhagn** [comment]
And down the rabbit-hole we went oO:
Seems like this behaviour is inherent in Chrome since version 64+, see this SO [thread](https://stackoverflow.com/questions/49161159/uncaught-domexception-failed-to-read-the-rules-property-from-cssstylesheet/49161468#49161468) and concerns a changed spec in the CSS Object Model, see [w3.org](https://www.w3.org/TR/cssom-1/#the-cssstylesheet-interface) on this.

Fixed it with the aforementioned `try ... catch` block and at seems to work with WAVE:

![WAVE screenshot](https://user-images.githubusercontent.com/12220779/52433083-75f36c80-2b0c-11e9-9f5c-50b5b235829e.png)

Updated the dependencies in [gbitest](https://github.com/timhagn/gbitest) as well  (and might you give it a go ; ). Thanks again @AlmeroSteyn!

**Comment by AlmeroSteyn** [comment]
Hey it's a pleasure!

I found the bit about 64 but not the change in the spec. Nice sleuthing!!!

I dit a test with `2.0.3` and it works like a charm! Thanks for fixing so fast :-)

**Comment by timhagn** [comment]
Happy it's working - and you're welcome and thanked - might have bitten me sooner or later ^^.

Didn't know about these changes, either, but I'm quite liking the specs (helped me a few times beforehand, too, like in [this case](https://blog.timhagn.com/restart-css3-animations-on-hover-without-javascript/) % ).

And thanks for a new word for my vocabulary (as German is my native tongue), 
hadn't heard about "sleuthing", that's kewl : ).

**Comment by AlmeroSteyn** [comment]
Hehe cool! Kinda word that is never used aside from in whodunit novels and github issues hahaha.

**Comment by timhagn** [comment]
Yip, "neighs, quoth in yesteryear though nevermore" ; ). 
And issue tracking is a kind of detective work, isn't it ^^?
So be thanked for both : ).

**Comment by EricSSartorius** [comment]
Not sure if I should re-open a new issue or not but I am currently using GBI v `0.2.4` and still have similar issues. In pages that both use GBI and also require 3rd party css style sheets (google fonts and yotpo widget in my case), I am getting something that reads:
```
Unable to read stylesheet rules for https://fonts.googleapis.com/css?family=Roboto:+400,500,700 DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules...
```
A similar error for the yotpo widget as well.

Is there a way around this? Not exactly sure how to handle it.

**Comment by timhagn** [comment]
@EricSSartorius Thought this was solved oO. Gonna look into it.

**Comment by timhagn** [comment]
Changed it to only `console.debug` with `e.message`, so one won't get overthrown by the stack trace ; ).

**Comment by EricSSartorius** [comment]
Ah ok, Yeah I didn't notice any crazy behavior only that I had a ton of messages in the console and it took me by surprise I guess.
