### ISSUE TITLE
activatePictureRef imageData is undefined sometimes in Safari

### ISSUE THREAD

**Issue by saschwarz** [timhagn/gatsby-background-image#94]
## Description

I'm running Rollbar on my gatsby blog and it is capturing this error a few times each week:

```
TypeError: undefined is not an object (evaluating 'i.srcSetWebp')
1
File "webpack:///./node_modules/gatsby-background-image/ImageUtils.js" line 240 col 13 in activatePictureRef
if (imageData.srcSetWebp) {
2
File "webpack:///./node_modules/gatsby-background-image/index.js" line 125 col 38 in BackgroundImage
_this.imageRef = (0, _ImageUtils.createPictureRef)((0, _extends2["default"])({}, props, {
3
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 3176 col 11 in jr
b = new b(c, f);
4
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 4263 col 103 in Zo
if (null === b.stateNode) null !== a && (a.alternate = null, b.alternate = null, b.effectTag |=...
5
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 5696 col 11 in Rs
var b = gk(a.alternate, a, W);
6
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 5685 col 9 in js
V = fk(V);
7
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 5441 col 11 in ws
Zj();
8
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 5239 col 66 in hs
1073741823 === b ? (T & nj) !== S && (T & (oj | pj)) === S ? Lj(a) : (Z(a), T === S && jg()) ...
9
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 7107 col 3 in iu
Rg(e, f);
10
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 7203 col 7 in [anonymous]
rk(b, g, a, e);
11
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 5492 col 12 in Ss
return a(b);
12
File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js" line 7202 col 5 in cu
ck(function () {
13
File "webpack:///./.cache/production-app.js" line 152 col 7 in [anonymous]
renderer(
```

According to Rollbar's telemetry it is only happening on Safari on the desktop and on iOS.

### Steps to reproduce

Unfortunately, I can't reproduce the issue after many attempts.

### Expected result

Looking at the code:

https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/src/lib/ImageRef.js#L109

somehow `imageData` is being set to undefined by either `getSelectedImage` or `getCurrentSrcData`.

### Actual result

I haven't dug into the code to see why they might be returning undefined. The site gets pretty much Safari traffic and only a very small percentage are encountering this error.

### Environment

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.13.39 => 2.18.7
    gatsby-background-image: ^0.8.14 => 0.8.19
    gatsby-cli: ^2.8.20 => 2.8.20
    gatsby-image: ^2.2.6 => 2.2.34
    gatsby-plugin-advanced-sitemap: ^1.4.4 => 1.4.5
    gatsby-plugin-algolia: ^0.3.3 => 0.3.4
    gatsby-plugin-catch-links: ^2.1.9 => 2.1.19
    gatsby-plugin-disqus: ^1.1.2 => 1.1.4
    gatsby-plugin-feed: ^2.3.5 => 2.3.23
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.29
    gatsby-plugin-manifest: ^2.2.4 => 2.2.31
    gatsby-plugin-mdx: ^1.0.41 => 1.0.59
    gatsby-plugin-netlify: ^2.1.19 => 2.1.27
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.16
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-rollbar: ^1.0.0 => 1.0.0
    gatsby-plugin-sass: ^2.1.12 => 2.1.24
    gatsby-plugin-sharp: ^2.2.9 => 2.3.5
    gatsby-remark-copy-linked-files: ^2.1.26 => 2.1.31
    gatsby-remark-images: ^3.1.7 => 3.1.35
    gatsby-remark-prismjs: ^3.3.3 => 3.3.25
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.28
    gatsby-remark-smartypants: ^2.1.2 => 2.1.17
    gatsby-remark-unwrap-images: ^1.0.1 => 1.0.1
    gatsby-source-filesystem: ^2.1.6 => 2.1.40
    gatsby-transformer-remark: ^2.6.9 => 2.6.39
    gatsby-transformer-sharp: ^2.2.4 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.13
```

**Comment by timhagn** [comment]
Hi @saschwarz,

happy new year and suchlike : ). Have you already tested it with `gbi v0.9.12`?

Best,

Tim.

**Comment by saschwarz** [comment]
HI @timhagn,

Sorry, I didn't see I was out of date with the latest. I'll deploy and test asap.

**Comment by timhagn** [comment]
Hi @saschwarz,

any news on this one?

Best,

Tim.

**Comment by saschwarz** [comment]
Hi @timhagn,

For some reason, I don't get any notifications when you comment!

It is definitely still happening with the latest code and the same stack trace. I was letting it run to make sure it wasn't client's hitting the site with old cached code bundles.

Let me know if there is something you'd like me to try
Steve

**Comment by timhagn** [comment]
Hi @saschwarz,

you're probably watching this issue manually from time to time, so not worries (might look into it inside a 14 day window, or the bot kicks in ; ) - so no worries.

I now added fallbacks in `getSelectedImage()` and `getCurrentSrcData()` both, but am still at a loss about the root of your issue. At first I thought `matchMedia` would be the culprit, but according to [caniuse](https://caniuse.com/#search=matchmedia) it would need some rather old browser versions for that being the reason...

Perhaps I need to know a little more about your use case (GraphQL queries, if you're using single, stacked, or art directed images for example) of `gbi` (some reproduction example would be even better ; ) to be able to give any more insights.

But for starters, please have a look at the just published `v0.9.14` of `gbi` and let's hope the fallbacks will suffice % ).

Best,

Tim.

**Comment by saschwarz** [comment]
HI @timhagn 

Thanks for the speedy reply/release. I've just deployed and will let you know when/if I get a rollbar traceback.

Here's how `gbi` is being used:

```
export default props => {
  const { image, title, subtitle } = props

  return (
    <div className="header-image-container">
      <BackgroundImage fluid={image} className={`header-image ${(title || subtitle) && 'titled'}`} style={{ 'backgroundPosition': 'center top' }}>
        {title ? <h1 className="title">{title}</h1> : null}
        {subtitle ? <h2 className="subtitle">{subtitle}</h2> : null}
      </BackgroundImage >
      <div>
)
```

Where the image is passed as a prop like so:

```
const image = mdx.frontmatter.image ? mdx.frontmatter.image.childImageSharp.fluid : null
```

**Comment by saschwarz** [comment]
@timhagn 

Unfortunately, it has happened again several more times:

```
TypeError: undefined is not an object (evaluating 'g.srcSetWebp')
  File "webpack:///./node_modules/gatsby-background-image/lib/ImageRef.js", line 116, in activatePictureRef
          if (imageData.srcSetWebp) {
  File "webpack:///./node_modules/gatsby-background-image/index.js", line 114, in BackgroundImage
        _this.imageRef = (0, _ImageRef.createPictureRef)((0, _extends2.default)({}, convertedProps, {
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 3176, in kr
      b = new b(c, f);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 4263, in Qo
      if (null === b.stateNode) null !== a && (a.alternate = null, b.alternate = null, b.effectTag |=...
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 5696, in ms
      var b = gk(a.alternate, a, W);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 5685, in gs
        V = fk(V);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 5441, in rs
              Zj();
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 5239, in es
        1073741823 === b ? (T & nj) !== S && (T & (oj | pj)) === S ? Lj(a) : (Z(a), T === S && jg()) ...
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 7107, in Ws
      Rg(e, f);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 7203, in [anonymous]
          rk(b, g, a, e);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 5492, in ls
        return a(b);
  File "webpack:///./node_modules/react-dom/cjs/react-dom.production.min.js", line 7202, in Qs
        ck(function () {
  File "webpack:///./.cache/production-app.js", line 154, in [anonymous]
          renderer(
```

**Comment by timhagn** [comment]
I now added a few fallbacks in the just published `v0.9.16` (..16 cause of some quirks in build mode after adding the falback check % ). Should it still happen, could you tell me on which versions of Safari these happen?

Best,

Tim.

**Comment by saschwarz** [comment]
Hi @timhagn,

Thanks again. I just rebuilt with 0.9.16 and pushed. I'll let you know if it happens again!

Steve

**Comment by timhagn** [comment]
We're at `v0.10.2`, meanwhile ; ).

**Comment by saschwarz** [comment]
Hi @timhagn,

It looks like this is fixed. I've published some popular articles on my blog that have generated a lot of traffic and haven't seen this error re-occur.  Thanks again for your persistence.

Steve
